### PR TITLE
chore: support generate the release notes automatically

### PR DESCRIPTION
**Pull request by LinuxSuRen**
See the official document https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs

### CODE REVIEW

**Comment by jaredLunde** [comment]
I think GoReleaser does this for the most part 🤔 

There's some customization here if something is missing: https://goreleaser.com/customization/release/

**Comment by LinuxSuRen** [comment]
Sure. I forgot goreleaser. So, close this PR?

**Comment by LinuxSuRen** [comment]
By the way, it looks like `goreleaser` does not support skipping some PRs which might be meaningless for the end-users.

**Comment by jaredLunde** [comment]
Yeah I think sticking with GoReleaser is probably a good idea. I like the idea of keeping the tooling to a minimum

**Comment by LinuxSuRen** [comment]
That is a good practice. 
No problem.

**Pull request closed without merging**
